# Generated by Django 4.2.17 on 2025-03-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="extra_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
