# Generated by Django 4.2.17 on 2025-03-11 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_alter_order_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="supplement",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
