# Generated by Django 4.2.17 on 2025-05-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0007_userbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='fixed_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
