# Generated by Django 5.2.15 on 2026-06-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_order_client_uuid_ledgerentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="balancenote",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("instapay", "انستا باي"),
                    ("cash", "كاش"),
                    ("wallet", "محفظة"),
                    ("bank_transfer", "تحويل بنكي"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="balancenote",
            name="note",
            field=models.TextField(blank=True, default=""),
        ),
    ]
