# Generated by Django 5.2.15 on 2026-06-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_balancenote_source_alter_balancenote_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
