# Generated by Django 5.2.15 on 2026-06-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_orderrevision"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="discount_note",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
