# Generated by Django 5.2.15 on 2026-07-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0014_order_discount_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="prev_balance_due",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
