# Generated by Django 4.2.17 on 2025-03-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
