# Generated by Django 4.2.17 on 2025-04-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_customuser_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, unique=True, verbose_name='first name'),
        ),
    ]
