# Generated by Django 4.2.17 on 2025-04-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_alter_customuser_first_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(fields=('first_name',), name='unique_first_name',
                                               violation_error_message='يوجد مستخدم بنفس الاسم بالفعل.'),
        ),
    ]
