# Generated by Django 4.2.17 on 2025-05-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_alter_customuser_options_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveConstraint(
            model_name='customuser',
            name='unique_first_name',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, error_messages={'unique': 'يوجد مستخدم بنفس الاسم بالفعل.'},
                                   max_length=150, unique=True, verbose_name='first name'),
        ),
    ]
