# Generated by Django 5.2.15 on 2026-06-17 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_customuser_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "مدير عام"),
                    ("manager", "مدير"),
                    ("staff", "موظف"),
                ],
                default="staff",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actor_username",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "إنشاء"),
                            ("update", "تعديل"),
                            ("delete", "حذف"),
                            ("payment", "دفعة"),
                            ("login", "تسجيل دخول"),
                            ("logout", "تسجيل خروج"),
                            ("print", "طباعة"),
                            ("export", "تصدير"),
                            ("sync", "مزامنة"),
                        ],
                        max_length=20,
                    ),
                ),
                ("entity", models.CharField(blank=True, default="", max_length=60)),
                ("object_id", models.CharField(blank=True, default="", max_length=60)),
                (
                    "object_repr",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("before", models.JSONField(blank=True, null=True)),
                ("after", models.JSONField(blank=True, null=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("device", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
