# Generated by Django 5.2.15 on 2026-06-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_superusers_to_super_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Backup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("path", models.CharField(blank=True, default="", max_length=500)),
                ("provider", models.CharField(default="local", max_length=20)),
                ("size", models.BigIntegerField(default=0)),
                ("status", models.CharField(default="ok", max_length=20)),
                ("kind", models.CharField(default="manual", max_length=20)),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
